{{- if .Values.configmap.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    {{- include "ezoidc.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | nindent 4 }}
{{- end }}
