{{- if .Values.role.create }}
{{- if .Values.role.namespaceSecrets }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ezoidc.roleName" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: {{ .Values.role.namespaceSecrets | toJson }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ezoidc.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ezoidc.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "ezoidc.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
