apiVersion: v1
kind: Service
metadata:
  name: {{ include "ezoidc.fullname" . }}
  labels:
    {{- include "ezoidc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3501
      protocol: TCP
      name: http
  selector:
    {{- include "ezoidc.selectorLabels" . | nindent 4 }}
