on:
  workflow_dispatch:

name: Helm Chart

permissions: {}

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          persist-credentials: false
      - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4
      - name: Login to GitHub Container Registry
        env:
          ACTOR: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$TOKEN" | helm registry login ghcr.io -u "$ACTOR" --password-stdin
      - run: make helm.push
